config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  get 'products/index'


  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, only: [:new, :create], module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
  end

  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
    match "/return_line_item" => "line_items#return_line_item", as: :return_line_item, via: [:get, :post]
  end

  resources :carts
  resources :orders do
    resources :sales_returns, only: [:destroy], module: :orders
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/scope_to_date_summary" => "orders#scope_to_date_summary",  via: [:get], on: :collection
    match "/retail" => "orders#retail", as: :retail, via: [:get], on: :collection
    match "/wholesale" => "orders#wholesale", as: :wholesale, via: [:get], on: :collection
    match "/sales_returns" => "orders#sales_returns", as: :sales_returns, via: [:get], on: :collection
    match "/return_order" => "orders#return_order", as: :return_order, via: [:get, :post]
  end

  resources :members do
    get :autocomplete_member_full_name, on: :collection
    resources :payments, only: [:new, :create], module: :members
    resources :interests, only: [:new, :create], module: :members

    match "/info" => "members#info", as: :info, via: [:get], on: :member
    match "/purchases" => "members#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "members#account_details", as: :account_details, via: [:get], on: :member

    resources :line_items, only: [:index], module: :members do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :members
    end
  end
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :regular_interest_rates, only: [:new, :create , :edit, :update]
  resources :irregular_interest_rates, only: [:new, :create , :edit, :update]
  resources :credits, only: [:index]
  namespace :accounts_receivables do
    resources :interests, only:[:create]
  end
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :categories
  resources :wholesales
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    get :autocomplete_stock_name_and_description, on: :collection
    match "/merge" => "stocks#merge",  via: [:post], on: :member
    resources :merge_stocks, only: [:new, :create], module: :stocks
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks
    match "/expired" => "stocks#expired", via: [:get], on: :collection
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/returned" => "stocks#returned", via: [:get], on: :collection
    match "/discontinued" => "stocks#discontinued", via: [:get], on: :collection
    match "/discontinue" => "stocks#discontinue", as: :discontinue, via: [:get, :post]
    match "/continue" => "stocks#continue", as: :continue, via: [:get, :post]
  end
  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :info, only: [:index]
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index] do
    get :autocomplete_account_name, on: :collection
  end
  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :employee_entries, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]
  resources :wholesale_pricelists, only: [:index]
  resources :sales_returns, only: [:new, :destroy]
end

app/controllers/products/stocks_controller.rb
module Products
  class StocksController < ApplicationController
    def new
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.build
    end

    def create
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.create(stock_params)
      @stock.employee = current_user
      if @stock.save
        redirect_to stock_histories_product_path(@product), notice: "New stock saved successfully."
        @stock.create_entry
        @stock.merge_stock
        @stock.set_stock_status_to_product
        @stock.purchased!
      else
        render :new
      end
    end
    def destroy 
    @stock = Stock.find(params[:id])
    @stock.create_entry_for_return
    @stock.destroy
    redirect_to stocks_url, alert: 'Stock deleted successfully.'
  end
    
    private
    def stock_params
      params.require(:stock).permit(:has_freight, :freight_amount, :discounted, :discount_amount, :merged, :payment_type, :supplier_id, :reference_number, :quantity, :date, :purchase_price, :serial_number, :expiry_date, :unit_price, :retail_price, :wholesale_price)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  autocomplete :product, :name_and_description, full: true

  def index
    if params[:name_and_description].present?
      @products = Product.search_by_name(params[:name_and_description]).page(params[:page]).per(30)
    else
      @products = Product.all.order(:name).page(params[:page]).per(30)
      respond_to do |format|
        format.html
        format.pdf do
          pdf = ProductsPdf.new(@products, view_context)
                send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Products Report.pdf"
        end
      end
    end
    authorize Product
  end

  def import
    begin
      Product.import(params[:file])
      redirect_to settings_url, notice: 'Products Imported'
    rescue
      redirect_to settings_url, notice: 'Invalid CSV File.'
    end
  end

  def new
    @product = Product.new
    @product.stocks.build
    authorize @product
  end

  def create
    @products = Product.all
    @product = Product.create(product_params)
    @product.check_stock_status
  end

  def stock_histories
    @product = Product.find(params[:id])
    @stocks = @product.stocks.order(merged: :asc).order(date: :desc).page(params[:page]).per(30)
  end

  def cash_sales
    @product = Product.find(params[:id])
    @sales = @product.line_items.cash
    @results = Kaminari.paginate_array(@sales).page(params[:page]).per(50)
  end

  def credit_sales
    @product = Product.find(params[:id])
    @sales = @product.line_items.credit
    @results = Kaminari.paginate_array(@sales).page(params[:page]).per(50)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    @product.update_prices
  end

  def scope_to_category
    @products = Product.by_category(params[:category]).page(params[:page]).per(50)
  end

  def reports
    @product = Product.find(params[:id])
    @sales = @product.line_items.credit
    @results = Kaminari.paginate_array(@sales).page(params[:page]).per(50)
  end
  def scope_to_date_cash_sales
    @product = Product.find(params[:id])
    @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : Time.now.beginning_of_day
    @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Time.now.end_of_day
    @line_items = @product.line_items.cash.select{|a| a.created_at.between?(@from_date, @to_date) }
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Products::SalesReportPdf.new(@product, @line_items, @from_date, @to_date, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Sales Report.pdf"
      end
    end
  end
  def scope_to_date_sales
    @product = Product.find(params[:id])
    @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : Time.now.beginning_of_day
    @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Time.now.end_of_day
    @line_items = @product.line_items.select{|a| a.created_at.between?(@from_date, @to_date) }
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Products::SalesReportPdf.new(@product, @line_items, @from_date, @to_date, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Sales Report.pdf"
      end
    end
  end

  def scope_to_date_credit_sales
    @product = Product.find(params[:id])
    @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : Time.now.beginning_of_day
    @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Time.now.end_of_day
    @orders = @product.line_items.credit.all.created_between({from_date: @from_date, to_date: @to_date})
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrdersPdf.new(@orders, @from_date, @to_date, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Sales Report.pdf"
      end
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :unit, :unit_quantity, :highest_unit, :price, :wholesale_price, :stock_alert_count, :category_id)
  end
end

app/views/products/histories/_cash_sales.html.erb
<div class="tab-pane <%='active' if current_page? cash_sales_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Customer </th>
        <th>QTY </th>
        <th>S/N </th>
        <th>Unit Cost </th>
        <th>Total Sales</th>
        <th>Cost of Goods Sold</th>
        <!-- <th> Income </th> -->

      </tr>
    </thead>
    <tbody>
      <% @results.to_a.sort_by(&:order_date).reverse.each do |line_item| %>
        <tr>
        <% if line_item.order.present? %>
          <td><%=line_item.order.date.strftime("%B %e, %Y") %></td>
          <td><%=line_item.order.try(:member)%></td>
          <td><%=line_item.converted_quantity %></td>
          <td><%=line_item.stock.serial_number %></td>
          <td><%=number_to_currency line_item.unit_cost %></td>
          <td><%=number_to_currency line_item.total_price %></td>
          <td><%=number_to_currency line_item.cost_of_goods_sold %></td>
          <!-- <td><%=number_to_currency line_item.income %></td> -->
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @results, :window => 1 %></center>
  </div>
</div>

app/views/products/histories/_credit_sales.html.erb
<div class="tab-pane <%='active' if current_page? credit_sales_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Customer </th>
        <th>QTY </th>
        <th>S/N </th>
        <th>Unit Cost </th>
        <th>Total Sales</th>
        <th>Cost of Goods Sold</th>
        <!-- <th> Income </th> -->

      
      </tr>
    </thead>
    <tbody>
      <% @results.each do |line_item| %>
        <tr>
        <% if line_item.order.present? %>
          <td><%=line_item.order.date.strftime("%B %e, %Y") %></td>
          <td><%=line_item.order.try(:member)%></td>
          <td><%=line_item.quantity %></td>
          <td><%=line_item.stock.serial_number %></td>
          <td><%=number_to_currency line_item.unit_cost %></td>
          <td><%=number_to_currency line_item.total_price %></td>
          <td><%=number_to_currency line_item.cost_of_goods_sold %></td>
          <!-- <td><%=number_to_currency line_item.income %></td> -->

        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @results, :window => 1 %></center>
  </div>
</div>

app/views/products/histories/_stock_histories.html.erb
<div class="tab-pane <%='active' if current_page? stock_histories_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Purchase Date</th>
        <th></th>
        <th>QTY </th>
        <!-- <th> QTY (Merged) </th> -->
        <!-- <th> Total Qty </th> -->
        <th> Sold </th>
        <th> IN STOCK </th>
        <th> S/N </th>
        <th> Unit Cost </th>
        <th> Discount </th>
        <th> Freight In </th>
        <th> Purchase Cost </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%@stocks.to_a.sort_by(&:date).reverse.each do |stock| %>
        <tr>
          <!-- <td><%# if stock.merged? %>
            <btn class="btn-danger btn-xs"> Merged </btn>
            <%# end %>
          </td> -->
          <td><%=stock.date.strftime('%B %e, %Y')%></td>
          <td>
            <small class='label label-<%="danger" if stock.out_of_stock?%><%= "warning" if stock.low_stock? && !stock.expired?%><%= "danger" if !stock.low_stock? && stock.expired?%><%= "danger" if stock.expired_and_low_stock?%>'><%=stock.status %></small>
          </td>
          <td><%=stock.converted_total_quantity %></td>
          <!-- <td><%#=stock.total_merged_stocks if !stock.merged?  %></td> -->
          <!-- <td><%#= stock.total_merged_stocks + stock.quantity if !stock.merged?  %></td> -->
          <td><%=stock.converted_sold_quantity %></td>
           <td><%=stock.converted_in_stock_quantity %></td>
          <td><%=stock.serial_number %></td>
          <td><%= number_to_currency stock.unit_price %></td>
          <td><%= number_to_currency stock.discount_amount %></td>
          <td><%= number_to_currency stock.freight_amount %></td>
          <td><%=number_to_currency stock.purchase_price %></td>
          <td><%= link_to stock_path(stock), method: :delete, title: 'Delete Stock', data: {confirm: 'Are you sure you want to delete this stock? This action can not be undone.'} do %>
            <span class="text-danger" title="Delete Stock" data-toggle='tooltip'><i class="fa fa-trash"></i></span>
          <% end %></td>
          <!-- <td><%#=link_to 'Merge', merge_stock_path(stock), class: 'btn btn-sm btn-warning', method: :post, data: {confirm: "Are you sure you want to merge this stock? THIS ACTION CANNOT BE UNDONE!"} if !stock.merged? && stock.total_merged_stocks == 0 && stock.product.stocks.count > 1%></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @stocks, :window => 1 %></center>
  </div>
</div>