config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  get 'products/index'


  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, only: [:new, :create], module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
  end

  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
    match "/return_line_item" => "line_items#return_line_item", as: :return_line_item, via: [:get, :post]
  end

  resources :carts
  resources :orders do
    resources :sales_returns, only: [:destroy], module: :orders
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/scope_to_date_summary" => "orders#scope_to_date_summary",  via: [:get], on: :collection
    match "/retail" => "orders#retail", as: :retail, via: [:get], on: :collection
    match "/wholesale" => "orders#wholesale", as: :wholesale, via: [:get], on: :collection
    match "/sales_returns" => "orders#sales_returns", as: :sales_returns, via: [:get], on: :collection
    match "/return_order" => "orders#return_order", as: :return_order, via: [:get, :post]
  end

  resources :members do
    get :autocomplete_member_full_name, on: :collection
    resources :payments, only: [:new, :create], module: :members
    resources :interests, only: [:new, :create], module: :members

    match "/info" => "members#info", as: :info, via: [:get], on: :member
    match "/purchases" => "members#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "members#account_details", as: :account_details, via: [:get], on: :member

    resources :line_items, only: [:index], module: :members do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :members
    end
  end
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :regular_interest_rates, only: [:new, :create , :edit, :update]
  resources :irregular_interest_rates, only: [:new, :create , :edit, :update]
  resources :credits, only: [:index]
  namespace :accounts_receivables do
    resources :interests, only:[:create]
  end
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :categories
  resources :wholesales
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    get :autocomplete_stock_name_and_description, on: :collection
    match "/merge" => "stocks#merge",  via: [:post], on: :member
    resources :merge_stocks, only: [:new, :create], module: :stocks
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks
    match "/expired" => "stocks#expired", via: [:get], on: :collection
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/returned" => "stocks#returned", via: [:get], on: :collection
    match "/discontinued" => "stocks#discontinued", via: [:get], on: :collection
    match "/discontinue" => "stocks#discontinue", as: :discontinue, via: [:get, :post]
    match "/continue" => "stocks#continue", as: :continue, via: [:get, :post]
  end
  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :info, only: [:index]
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index] do
    get :autocomplete_account_name, on: :collection
  end
  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :employee_entries, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]
  resources :wholesale_pricelists, only: [:index]
  resources :sales_returns, only: [:new, :destroy]
end

app/models/accounting/amount.rb
module Accounting
  class Amount < ApplicationRecord
    belongs_to :account, class_name: "Accounting::Account"
    belongs_to :entry, class_name: "Accounting::Entry"

    validates :type, :amount, :entry, :account, presence: true
    def account_name=(name)
        self.account = Accounting::Account.find_by_name(name)
      end

      protected

      # Support constructing amounts with account = "name" syntax
      def account_with_name_lookup=(v)
        if v.kind_of?(String)
          ActiveSupport::Deprecation.warn('Plutus was given an :account String (use account_name instead)', caller)
          self.account_name = v
        else
          self.account_without_name_lookup = v
        end
      end
      alias_method_chain :account=, :name_lookup
    end
end

app/models/accounting/credit_amount.rb
module Accounting
  class CreditAmount < Amount
  end
end

app/models/accounting/debit_amount.rb
module Accounting
  class DebitAmount < Amount
  end
end

app/controllers/accounting/accounting_controller.rb
class AccountingController < ApplicationController
  def index
  end
end 

app/controllers/accounting/accounts_controller.rb
module Accounting
  class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :edit, :update, :destroy]
    before_action :set_type

    autocomplete :accounting_account, :name, full: true

    def index
      if params[:name].present?
        @accounts = type_class.search_by_name(params[:name])
      else
        @accounts = type_class.all.order(:code)
      end
      authorize @accounts
    end

    def show
    end

    def new
      @account = type_class.new
    end

    def edit
    end

    def create
      @accounts = Accounting::Account.all.order(:type)
      @account = Accounting::Account.create(account_params)
    end

    def update
      @accounts = Accounting::Account.all
      @account = Accounting::Account.find(params[:id])
      @account.update_attributes(account_params)
    end

    def activate
      @account = Accounting::Account.find(params[:id])
      @account.active!
      redirect_to accounting_index_url
    end
    def deactivate
      @account = Accounting::Account.find(params[:id])
      @account.inactive!
      redirect_to accounting_index_url
    end

    def destroy
      @account.destroy
      redirect_to accounts_url
    end

    private

    def set_type
      @type = type
    end

    def type
      Accounting::Account.types.include?(params[:type]) ? params[:type] : "Accounting::Account"
    end

    def type_class
      type.constantize
    end

    def set_account
      @account = type_class.find(params[:id])
    end

    def account_params
      params.require(type.underscore.gsub('/', '_').to_sym).permit(:name, :type, :code)
    end

  end
end

app/controllers/accounting/balance_sheet_controller.rb
class Accounting::BalanceSheetController < ApplicationController
  def index
    first_entry = Accounting::Entry.order('date ASC').first
    @from_date = first_entry ? first_entry.date: Date.today
    @to_date = params[:date] ? Date.parse(params[:date]) : Date.today
    @assets = Accounting::Asset.all
    @liabilities = Accounting::Liability.all
    @equity = Accounting::Equity.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/accounting/credit_payments_controller.rb
module Accounting
  class CreditPaymentsController < ApplicationController

    def new
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.create(entry_params)
      @entry.commercial_document = @line_item.order
      @entry.recorder = current_user
      if @entry.save
        @line_item.cash!
        redirect_to @line_item.stock.product, notice: "Payment saved successfully."
      else
        render :new
      end
      authorize @entry
    end

    def show
      @entry = Accounting::Entry.find(params[:id])
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end
end

app/controllers/accounting/dashboard_controller.rb
module Accounting
  class DashboardController < ApplicationController
    def index
      authorize [:accounting, :dashboard]
    end
  end
end

app/controllers/accounting/employee_entries_controller.rb
module Accounting 
  class EmployeeEntriesController < ApplicationController 
    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to accounting_entries_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:commercial_document_id, :commercial_document_type, :date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end 
end

app/controllers/accounting/entries_controller.rb
module Accounting
  class EntriesController < ApplicationController

    autocomplete :entry, :description, full: true, class_name: 'Accounting::Entry'

    def index
      if params[:description].present?
      @entries = Accounting::Entry.search_by_name(params[:description]).order(:date).page(params[:page]).per(30)

      else
        @entries = Accounting::Entry.includes(:commercial_document, :recorder).all.order('date DESC').page(params[:page]).per(30)
        @from_date = params[:from_date] ? Time.parse(params[:from_date]) : Time.now.beginning_of_day
        @to_date = params[:to_date] ? Time.parse(params[:to_date]) : Time.now.end_of_day
        respond_to do |format|
          format.html
          format.pdf do
            pdf = EntriesPdf.new(@entries, @from_date, @to_date, view_context)
              send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Entries Report.pdf"
          end
        end
      end
      authorize @entries
    end

    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entries = Accounting::Entry.all
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to accounting_entries_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    def show
      @entry = Accounting::Entry.find(params[:id])
    end

    def autocomplete
      @entries = Accounting::Entry.all
      @names = @entries.select('description').map(&:description)
      render json: @names
    end

    def scope_to_date
      @entries = Accounting::Entry.created_between(params[:from_date], params[:to_date])
      @from_date = params[:from_date] ? Time.parse(params[:from_date]) : Time.now.beginning_of_day
      @to_date = params[:to_date] ? Time.parse(params[:to_date]) : Time.now.end_of_day
      respond_to do |format|
        format.html
        format.pdf do
          pdf = EntriesPdf.new(@entries, @from_date, @to_date, view_context)
            send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Entries Report.pdf"
        end
      end
    end

    def destroy
      @entry = Accounting::Entry.find(params[:id])
      if @entry.commercial_document_type == "Refund"
        if Refund.where(id: @entry.commercial_document_id).last == !nil
          @refund = Refund.find(@entry.commercial_document_id)
          @refund.stock.update_attributes!(quantity: @refund.quantity)
          @refund.destroy
        end
      end
      @entry.destroy
      redirect_to accounting_entries_path, alert: 'Entry has been deleted.'
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end
end

app/controllers/accounting/income_statement_controller.rb
class Accounting::IncomeStatementController < ApplicationController
  def index
    @from_date = params[:from_date] ? Date.parse(params[:from_date]) : Date.today.at_beginning_of_month
    @to_date = params[:to_date] ? Date.parse(params[:to_date]) : Date.today
    @revenues = Accounting::Revenue.all
    @expenses = Accounting::Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.pdf do
        pdf = Accounting::IncomeStatementPdf.new(@revenues, @expenses,  @from_date, @to_date, view_context)
        send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Income Statement.pdf"
      end
    end
  end
end

app/controllers/accounting/member_entries_controller.rb
module Accounting 
  class MemberEntriesController < ApplicationController 
    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to accounting_entries_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:commercial_document_id, :commercial_document_type, :date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end 
end

app/views/accounting/entries/_index.html.erb
<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.date.strftime("%B %e, %Y") %></td>

    <td><%=link_to entry.description.truncate(200), accounting_entry_path(entry) %></td>
    <!-- <td><%#=entry.commercial_document || "Proprietor" %></td> -->
    <td><%=entry.recorder.try(:full_name) %></td>
    <td><%entry.debit_amounts.each do |debit| %>
      <small><%= debit.account.try(:name) %> <span class='pull-right'><%=number_to_currency debit.amount %></span></small><br>
      <% end %>
      </td>
       <td><%entry.credit_amounts.each do |credit| %>
      <small><%= credit.account.try(:name) %> <span class='pull-right'><%=number_to_currency credit.amount %></span></small><br>
      <% end %>
      </td>
  </tr>
<% end %>

app/views/accounting/entries/index.html.erb
<div id="entryModal" class="modal fade"></div>
<div class="row">
  <div class="col-md-12">
  	<div class="box box-solid">
    	<div class="box-body">
				<div class="col-md-4">
			  	<ul class="nav navbar-nav">
			      <li class="dropdown">
			        <button href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Show Activity <b class="caret"></b></button>
			        <ul class="dropdown-menu dropdown-menu-right">
			          <li><%=link_to 'This Day', scope_to_date_accounting_entries_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') %></li>
						    <li> <%=link_to 'This Week', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') %></li>
						    <li> <%=link_to 'This Month', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') %></li>
			        </ul>
			      </li>
			    </ul>
				</div>
				<div class="col-md-4">
			    <%=form_tag accounting_entries_path, method: :get do %>
			      <div class="input-group stylish-input-group" id="entry-prefetch">
			        <%= autocomplete_field_tag "description", params[:description], autocomplete_entry_description_accounting_entries_path, class: 'form-control', placeholder: 'Search Entry...' %>
			        <span class="input-group-btn">
			          <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
			            <i class="fa fa-search"></i>
			          <% end %>
			        </span>
			      </div>
			    <% end %>
				</div>
				<div class="col-md-4">
				<ul class="nav navbar-nav pull-right">
			      <li class="dropdown">
			        <button href="#" class="dropdown-toggle btn btn-danger" data-toggle="dropdown" aria-expanded="false">New Entry <b class="caret"></b></button>
			        <ul class="dropdown-menu dropdown-menu-right">
			          <li><%=link_to 'New Entry', new_accounting_entry_path %></li>
						    <!-- <li> <%#=link_to 'New Entry (Member)', new_accounting_member_entry_path%></li>
						    <li> <%#=link_to 'New Entry (Employee)', new_accounting_employee_entry_path %></li>
						    <li> <%#=link_to 'New Entry (Supplier)', new_accounting_supplier_entry_path %></li> -->

			        </ul>
			      </li>
			    </ul>
				</div>
			</div>
			<hr>
			<div class="row">
			  <div class="col-md-3">
			    <span class="pull-right title">Filter Date:</span>
			  </div>
			  <div class="col-md-9">
			    <%= form_tag({:action => 'index'}, {:method => :get})  do %>
			      <div class="row">
			        <div class="col-md-4">
			          <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control'%>
			        </div>
			        <div class="col-md-4">
			          <%= text_field_tag :to_date, @to_date, :class => 'form-control datepicker'%>
			        </div>
			        <div class="col-md-4">
			        	<button type="submit" class="btn btn-success active"> Go </button>
			          <%=link_to "PDF", accounting_entries_path(format: 'pdf', from_date: @from_date, to_date: @to_date), class: "btn btn-default active"%>
			        </div>
			      </div>
			    <% end %>
			  </div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-12">
				  <div class="card">
				    <div class="header">
				    </div>
						<div class="content">
							<div class="table table-responsive">
								<table class="table table-striped">
									<thead>
										<tr class="title">
			                <th> Date </th>
											<th> Description </th>
			                <!-- <th> Proprietor / Supplier </th> -->
											<th> Employee </th>
											<th> Debit</th>
											<th> Credit </th>
										</tr>
									</thead>
									<tbody class="entry-index">
										<%=render 'index' %>
									</tbody>
								</table>
								<div class="modal-footer">
				          <center><%= paginate @entries, :window => 1 %></center>
				        </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/accounting/entries/new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for @entry, html: { style: "display:inline;" } do |f| %>
      <div class="modal-header">
        <h3 class="modal-title">New Entry</h3>
      </div>
      <div class="modal-body">
        <ul class="errors text-danger">
        </ul>
        <div class="row">
          <div class="col-md-6">
            <%=f.input :date, as: :string, input_html: { class: "datepicker" } %>
          </div>
          <div class="col-md-6">
            <%=f.input :reference_number %>
          </div>
        </div>
        <%=f.input :description %>

        <%=f.simple_fields_for :debit_amounts do |ff| %>
          <%=ff.input :amount %>
          <%=ff.input :account, collection: Accounting::Account.active.all.pluck(:name), label: 'Debit Account' %>
        <% end %>
        <%=f.simple_fields_for :credit_amounts do |ff| %>
          <%=ff.input :amount, as: :hidden %>
          <%=ff.input :account, collection: Accounting::Account.active.all.pluck(:name), label: 'Credit Account' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", accounting_entries_path, class: "btn pull-left", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $("#accounting_entry_debit_amounts_attributes_0_account").select2({
    theme: "bootstrap",
    placeholder: 'Select Account',
    width: '100%',
    dropdownAutoWidth : true
  });
  $("#accounting_entry_credit_amounts_attributes_0_account").select2({
    theme: "bootstrap",
    placeholder: 'Select Account',
    width: '100%',
    dropdownAutoWidth : true
  });
</script>

app/views/accounting/entries/new.js.erb
$("#entryModal").html("<%= escape_javascript(render 'new') %>")
$('#entryModal').modal({backdrop: 'static', keyboard: false, show: true})
$('.datepicker').datepicker({
	format: "yyyy/mm/dd/",
	orientation: "auto bottom",
	todayHighlight: 'true',
	autoclose: 'true'
	});
$("#accounting_entry_debit_amounts_attributes_0_account").select2({
  theme: "bootstrap",
  placeholder: 'Select Account',
  width: '100%',
  dropdownAutoWidth : true
});
$("#accounting_entry_credit_amounts_attributes_0_account").select2({
  theme: "bootstrap",
  placeholder: 'Select Account',
  width: '100%',
  dropdownAutoWidth : true
});

app/views/accounting/entries/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="box box-solid">
			<div class="box-header">
				<h4>Entry Details</h4>
					<div class="pull-right">
				  	<ul class="nav navbar-nav">
				      <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> <i class="fa fa-cog"></i></a>
				        <ul class="dropdown-menu dropdown-menu-right">
				          <li><%=link_to 'Delete', accounting_entry_path(@entry), method: :delete, data: {confirm: 'Are you sure you want to DELETE this entry? THIS ACTION CANNOT BE UNDONE.'} %></li>
				        </ul>
				      </li>
				    </ul>
				  </div>
				</h4>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<p><strong>Date</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.date.strftime("%B %e, %Y") %></span>
						<hr>
						<p><strong>Description</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.description %></span><br>
						<hr>
						<p><strong>Member/Employee/Supplier:</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.commercial_document.try(:full_name) %></span><br>
						<hr>
						<p><strong>Reference Number</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.reference_number%></span>
						<hr>
						<p><strong>Debited Account(s)</strong></p>
						<%@entry.debit_amounts.each do |d|%>
							<div class="row">
								<div class="col-md-12">
									&nbsp &nbsp &nbsp<%=d.account.name %><span class="pull-right"><%=number_to_currency d.amount %></span>
								</div>
							</div>
						<%end %>
						<hr>

						<p><strong>Credited Account(s)</strong></p>
						<%@entry.credit_amounts.each do |d|%>
							<div class="row">
								<div class="col-md-12">
									&nbsp &nbsp &nbsp<%=d.account.name %> <span class="pull-right"><%=number_to_currency d.amount %></span>
								</div>
							</div>
						<% end %>
						<br>
						<div class="modal-footer">
							<%= link_to "Back", accounting_entries_path, class: 'btn btn-default pull-left' %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="entryModal" class="modal fade"></div>